# Random Forest model on Titanic Dataset

In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [42]:
data=pd.read_csv('titanic_eda.csv')

In [43]:
data.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  male  Q  S  \
0            1         0       3  22.0      1      0   7.2500     1  0  1   
1            2         1       1  38.0      1      0  71.2833     0  0  0   
2            3         1       3  26.0      0      0   7.9250     0  0  1   
3            4         1       1  35.0      1      0  53.1000     0  0  1   
4            5         0       3  35.0      0      0   8.0500     1  0  1   

  AgeGroup  
0    Adult  
1    Adult  
2    Adult  
3    Adult  
4    Adult

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 11 columns):
PassengerId    714 non-null int64
Survived       714 non-null int64
Pclass         714 non-null int64
Age            714 non-null float64
SibSp          714 non-null int64
Parch          714 non-null int64
Fare           714 non-null float64
male           714 non-null int64
Q              714 non-null int64
S              714 non-null int64
AgeGroup       714 non-null object
dtypes: float64(2), int64(8), object(1)
memory usage: 61.5+ KB


In [45]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   714.000000  714.000000  714.000000  714.000000  714.000000   
mean    448.582633    0.406162    2.236695   29.625588    0.512605   
std     259.119524    0.491460    0.838250   14.323792    0.929783   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     222.250000    0.000000    1.000000   20.125000    0.000000   
50%     445.000000    0.000000    2.000000   28.000000    0.000000   
75%     677.750000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   65.000000    5.000000   

            Parch        Fare        male           Q           S  
count  714.000000  714.000000  714.000000  714.000000  714.000000  
mean     0.431373   21.308270    0.634454    0.039216    0.778711  
std      0.853289   14.655611    0.481921    0.194244    0.415405  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    8.050000    0.000000    0.000000    1.000000  
50%      0.000000   15.741700    1.000000    0.000000    1.000000  
75%      1.000000   33.375000    1.000000    0.000000    1.000000  
max      6.000000   71.283300    1.000000    1.000000    1.000000

In [46]:
data.drop(['PassengerId','Fare','AgeGroup'],axis=1,inplace=True)

In [47]:
X=data.iloc[:,1:].values
X.shape

(714, 7)

In [48]:
y=data.iloc[:,:1].values
y.shape

(714, 1)

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 , random_state=0)

In [50]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [51]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 20, criterion='entropy')

clf.fit(X_train, y_train)

C:\Users\himan\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [52]:
y_pred = clf.predict(X_test)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [53]:
y_test

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
    

In [54]:
from sklearn import metrics
from sklearn.metrics import  confusion_matrix

In [55]:
cm=confusion_matrix(y_test,y_pred)

In [56]:
cm

array([[97, 28],
       [29, 61]], dtype=int64)

In [57]:
metrics.accuracy_score(y_test, y_pred)

0.7348837209302326